name: Analyze-bundle

on:
  workflow_dispatch:
  pull_request:
    branches: [master]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout wiki
        uses: actions/checkout@v2
        with:
          repository: ${{github.repository}}.wiki

      - name: Analyze bundle
        run: |
          echo 'analyzed-bundle-0824-1' > test-wiki.md

      - name: Push to wiki
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@example.com"
          git add .
          git diff-index --quiet HEAD || git commit -m "Update analyzed bundle" && git push
