name: Compare bundle stats

on:
  pull_request:
    types: [opened]
  workflow_dispatch:

jobs:
  build-head:
    name: 'Build head'
    if: ${{ !startsWith(github.head_ref, 'dependabot-npm_and_yarn-') }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        ref: ${{ github.event.inputs.head_branch || github.head_ref }}
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npx webpack --json=dist/stats.json
    - name: Upload stats
      uses: actions/upload-artifact@v2
      with:
        name: head-stats
        path: ./dist/stats.json
    - name: Create comment
      uses: actions/github-script@v4
      with:
        script: |
          const fs = require('fs')
          const text = fs.readFileSync('./dist/package-size-list.textile', 'utf8')
          const replaced = text
            .replace(/  /g, '- ')
            .replace(/\n/g, '<br>\n')
            .replace(/<self>/g, '(self)')
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `<details><summary>Packageサイズ一覧</summary>${replaced}</details>`
          })

  build-base:
    name: 'Build base'
    if: ${{ !startsWith(github.head_ref, 'dependabot-npm_and_yarn-') }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        ref: ${{ github.base_ref }}
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npx webpack --json=dist/stats.json
    - name: Upload stats
      uses: actions/upload-artifact@v1
      with:
        name: base-stats
        path: ./dist/stats.json

  compare:
    name: 'Compare base & head bundle sizes'
    if: ${{ !startsWith(github.head_ref, 'dependabot-npm_and_yarn-') }}
    runs-on: ubuntu-latest
    needs: [build-base, build-head]
    steps:
    - uses: actions/checkout@v1
    - name: Download base artifact
      uses: actions/download-artifact@v1
      with:
        name: base-stats
    - name: Download head artifact
      uses: actions/download-artifact@v1
      with:
        name: head-stats
    - name: Diff between base & head
      uses: chronotruck/webpack-stats-diff-action@1.0.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        base_stats_path: ./base-stats/stats.json
        head_stats_path: ./head-stats/stats.json
        announcement_percentage_threshold_increase: 1
        announcement_percentage_threshold_decrease: -1
