name: Update bundle size list

on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: ${{github.repository}}

    - name: Install dependencies
      run: npm ci

    - name: Build assets
      run: npm run build

    - name: Checkout wiki
      uses: actions/checkout@v2
      with:
        repository: ${{github.repository}}.wiki
        ref: master
        path: .wiki

    - name: Move package-size-list.textile
      run: mv ./dist/package-size-list.textile .wiki/Bundleサイズ一覧.textile

    - name: Push to wiki
      working-directory: .wiki
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@example.com"
        git add .
        git diff-index --quiet HEAD || git commit -m "Update analyzed bundle" && git push
