name: visual regression testing

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  serve:
    name: serve
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10.16.3
      - run: npm install

  vrt:
    name: backstopjs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10.16.3
      - run: npm install
      - run: npx cross-env REFERENCE=true TOKEN=829c19e5-bbe6-4679-9a10-83fae4c13c06 INDEX=7 backstop reference --config=backstop.config.js
      - run: npx cross-env REFERENCE=false TOKEN=829c19e5-bbe6-4679-9a10-83fae4c13c06 INDEX=7 backstop test --config=backstop.config.js
