name: visual regression testing

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  serve:
    name: serve
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10.16.3
      - run: npm run reinstall
      - run: webpack-dev-server

  vrt:
    name: backstopjs
    runs-on: ubuntu-latest
    steps:
      - run: echo '/// vrt test'
